services:
  pixel-ghost-api:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - ENV=dev
    restart: always

  pixel-ghost-frontend:
    build:
      context: ./frontend
    ports:
      - 5173:80
    depends_on:
      - pixel-ghost-api
    restart: always
