services:
  pixel-ghost-api:
    build:
      context: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - ENV=prod
      - API_KEY=${API_KEY}
    restart: always

  pixel-ghost-frontend:
    build:
      context: ./frontend
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
    depends_on:
      - pixel-ghost-api
    restart: always

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - pixel-ghost-frontend

volumes:
  caddy_data:
  caddy_config:
