services:
  pixel-ghost-api:
    build:
      context: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - ENV=prod
    restart: always

  pixel-ghost-frontend:
    build:
      context: ./frontend
    ports:
      - "${APP_PORT:-8080}:80"
    depends_on:
      - pixel-ghost-api
    restart: always
