/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description Health check endpoint.
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Tasks
         * @description List all submitted tasks with their IDs.
         */
        get: operations["list_all_tasks_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description Get the status of a submitted task.
         */
        get: operations["get_task_status_task_status__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task/result/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Result
         * @description Get the result of a completed task (e.g., download the output file).
         */
        get: operations["get_task_result_task_result__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/lsb/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encode Text In Image
         * @description Encode a hidden text message into an image using LSB steganography.
         */
        post: operations["encode_text_in_image_text_lsb_encode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/lsb/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decode Text From Image
         * @description Decode and extract a hidden text message from an encoded image.
         */
        post: operations["decode_text_from_image_text_lsb_decode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/lsb_random/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lsb Random Encode Text In Image
         * @description Encode a hidden text message into an image using LSB steganography with randomized pixel selection.
         */
        post: operations["lsb_random_encode_text_in_image_text_lsb_random_encode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/lsb_random/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lsb Random Decode Text From Image
         * @description Decode and extract a hidden text message from an encoded image using LSB steganography with randomized pixel selection.
         */
        post: operations["lsb_random_decode_text_from_image_text_lsb_random_decode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/lsb_random_enc/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lsb Random Enc Encode Text In Image
         * @description Encode and encrypt a hidden text message into an image using LSB steganography with randomized pixel selection.
         */
        post: operations["lsb_random_enc_encode_text_in_image_text_lsb_random_enc_encode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text/lsb_random_enc/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lsb Random Enc Decode Text From Image
         * @description Decode and decrypt a hidden text message from an encoded image using LSB steganography with randomized pixel selection.
         */
        post: operations["lsb_random_enc_decode_text_from_image_text_lsb_random_enc_decode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/lsb/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encode Image In Image
         * @description Encode a secret image into a cover image using basic LSB steganography.
         */
        post: operations["encode_image_in_image_image_lsb_encode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/lsb/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decode Image From Image
         * @description Decode and extract a hidden image from a stego image using basic LSB steganography.
         */
        post: operations["decode_image_from_image_image_lsb_decode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/lsb_random/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encode Image In Image Random
         * @description Encode a secret image into a cover image using LSB steganography with pseudorandom pixel selection.
         */
        post: operations["encode_image_in_image_random_image_lsb_random_encode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/lsb_random/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decode Image From Image Random
         * @description Decode and extract a hidden image from a stego image using LSB steganography with pseudorandom pixel selection.
         */
        post: operations["decode_image_from_image_random_image_lsb_random_decode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/lsb_random_enc/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encode Image In Image Encrypted
         * @description Encode and encrypt a secret image into a cover image using LSB steganography with pseudorandom pixel selection.
         */
        post: operations["encode_image_in_image_encrypted_image_lsb_random_enc_encode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/lsb_random_enc/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decode Image From Image Encrypted
         * @description Decode and decrypt a hidden image from a stego image using LSB steganography with pseudorandom pixel selection.
         */
        post: operations["decode_image_from_image_encrypted_image_lsb_random_enc_decode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/dct/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dct Encode Image
         * @description Encode a secret image into a cover image using DCT steganography.
         */
        post: operations["dct_encode_image_image_dct_encode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image/dct/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dct Decode Image
         * @description Decode and extract a hidden image from an encoded image using DCT steganography.
         */
        post: operations["dct_decode_image_image_dct_decode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_dct_decode_image_image_dct_decode_post */
        Body_dct_decode_image_image_dct_decode_post: {
            /** Image */
            image: string;
        };
        /** Body_dct_encode_image_image_dct_encode_post */
        Body_dct_encode_image_image_dct_encode_post: {
            /** Cover Image */
            cover_image: string;
            /** Secret Image */
            secret_image: string;
        };
        /** Body_decode_image_from_image_encrypted_image_lsb_random_enc_decode_post */
        Body_decode_image_from_image_encrypted_image_lsb_random_enc_decode_post: {
            /** Stego Image */
            stego_image: string;
            /** Key */
            key: string;
        };
        /** Body_decode_image_from_image_image_lsb_decode_post */
        Body_decode_image_from_image_image_lsb_decode_post: {
            /** Stego Image */
            stego_image: string;
        };
        /** Body_decode_image_from_image_random_image_lsb_random_decode_post */
        Body_decode_image_from_image_random_image_lsb_random_decode_post: {
            /** Stego Image */
            stego_image: string;
            /** Key */
            key: string;
        };
        /** Body_decode_text_from_image_text_lsb_decode_post */
        Body_decode_text_from_image_text_lsb_decode_post: {
            /** Image */
            image: string;
        };
        /** Body_encode_image_in_image_encrypted_image_lsb_random_enc_encode_post */
        Body_encode_image_in_image_encrypted_image_lsb_random_enc_encode_post: {
            /** Cover Image */
            cover_image: string;
            /** Secret Image */
            secret_image: string;
            /** Key */
            key: string;
        };
        /** Body_encode_image_in_image_image_lsb_encode_post */
        Body_encode_image_in_image_image_lsb_encode_post: {
            /** Cover Image */
            cover_image: string;
            /** Secret Image */
            secret_image: string;
        };
        /** Body_encode_image_in_image_random_image_lsb_random_encode_post */
        Body_encode_image_in_image_random_image_lsb_random_encode_post: {
            /** Cover Image */
            cover_image: string;
            /** Secret Image */
            secret_image: string;
            /** Key */
            key: string;
        };
        /** Body_encode_text_in_image_text_lsb_encode_post */
        Body_encode_text_in_image_text_lsb_encode_post: {
            /** Image */
            image: string;
            /** Message */
            message: string;
        };
        /** Body_lsb_random_decode_text_from_image_text_lsb_random_decode_post */
        Body_lsb_random_decode_text_from_image_text_lsb_random_decode_post: {
            /** Image */
            image: string;
            /** Key */
            key: string;
        };
        /** Body_lsb_random_enc_decode_text_from_image_text_lsb_random_enc_decode_post */
        Body_lsb_random_enc_decode_text_from_image_text_lsb_random_enc_decode_post: {
            /** Image */
            image: string;
            /** Key */
            key: string;
        };
        /** Body_lsb_random_enc_encode_text_in_image_text_lsb_random_enc_encode_post */
        Body_lsb_random_enc_encode_text_in_image_text_lsb_random_enc_encode_post: {
            /** Image */
            image: string;
            /** Message */
            message: string;
            /** Key */
            key: string;
        };
        /** Body_lsb_random_encode_text_in_image_text_lsb_random_encode_post */
        Body_lsb_random_encode_text_in_image_text_lsb_random_encode_post: {
            /** Image */
            image: string;
            /** Message */
            message: string;
            /** Key */
            key: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_all_tasks_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_task_status_task_status__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_result_task_result__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encode_text_in_image_text_lsb_encode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_encode_text_in_image_text_lsb_encode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decode_text_from_image_text_lsb_decode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_decode_text_from_image_text_lsb_decode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lsb_random_encode_text_in_image_text_lsb_random_encode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_lsb_random_encode_text_in_image_text_lsb_random_encode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lsb_random_decode_text_from_image_text_lsb_random_decode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_lsb_random_decode_text_from_image_text_lsb_random_decode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lsb_random_enc_encode_text_in_image_text_lsb_random_enc_encode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_lsb_random_enc_encode_text_in_image_text_lsb_random_enc_encode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lsb_random_enc_decode_text_from_image_text_lsb_random_enc_decode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_lsb_random_enc_decode_text_from_image_text_lsb_random_enc_decode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encode_image_in_image_image_lsb_encode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_encode_image_in_image_image_lsb_encode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decode_image_from_image_image_lsb_decode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_decode_image_from_image_image_lsb_decode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encode_image_in_image_random_image_lsb_random_encode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_encode_image_in_image_random_image_lsb_random_encode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decode_image_from_image_random_image_lsb_random_decode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_decode_image_from_image_random_image_lsb_random_decode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encode_image_in_image_encrypted_image_lsb_random_enc_encode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_encode_image_in_image_encrypted_image_lsb_random_enc_encode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decode_image_from_image_encrypted_image_lsb_random_enc_decode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_decode_image_from_image_encrypted_image_lsb_random_enc_decode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dct_encode_image_image_dct_encode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_dct_encode_image_image_dct_encode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dct_decode_image_image_dct_decode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_dct_decode_image_image_dct_decode_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
